runtime: nodejs22
service: default

handlers:
  - url: /assets
    static_dir: dist/assets
    secure: always

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json|txt|woff|woff2))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json|txt|woff|woff2)$
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always