steps:
  - name: node:22
    entrypoint: npm
    args: ["ci"]
    dir: frontend

  - name: node:22
    entrypoint: npm
    args: ["run", "build"]
    dir: frontend

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - gcloud app deploy app.yaml --quiet
    dir: frontend

timeout: 1600s